### ISSUE TITLE
Abstracting common styles in their own class

### ISSUE THREAD

**Issue by zannain** [romanovichk/colmar#3]
Good work in organizing the stylesheet to match the mockups markup. In fact grouping styles by section is recommended by [Googles HTML/CSS style guide](https://google.github.io/styleguide/htmlcssguide.html#Type_Selectors). I noticed in the _Universal Styles_ areas were styles were being [repeated](https://github.com/romanovichk/colmar/blob/master/resources/css/styles.css#L20-L32). A concept you will likely come across in development is [Dont-Repeat-Yourself](http://deviq.com/don-t-repeat-yourself/). With stylesheets, rather than repeating `padding-bottom:32px`

```css
.content2 h1 {
  padding-top: 32px;
}

.content3 h1 {
  text-align: center;
  padding-bottom: 32px;
}

.content4 h1 {
  text-align: center;
  padding-top: 32px;
  width: 100%;
}
```
An alternative approach could be

```
.pb-32 {
     padding-bottom:32;
}
```

Now the `pb-32` class can be used for `h1` tags but also anywhere else in the markup. Also if you want to update the style later, rather than finding the style everywhere that it is repeated, it is a simple matter of updating that one style once and every element with that class will be updated. This is actually how CSS frameworks like [Bootstrap](https://getbootstrap.com/) are designed!
